### ISSUE TITLE
Mojave Compatibility

### ISSUE THREAD

**Issue by rayfarer** [pineapplemachine/mwde#1]
Does this tool work with Mojave? I followed the instructions, but when I open the Morrowind Dialog Explorer application I receive the following error message:

The application “Morrowind Dialog Explorer” can’t be opened.

Thanks! I am very interested in using the explorer and I just wanted to check to see if there is a compatibility issue or if I'm doing something wrong.

**Comment by rayfarer** [comment]
**Update:** I used chmod it to make it executable, and was able to open the application. But now I am getting:

`python: can't open file 'src/dialog_explorer.py': [Errno 2] No such file or directory`

**Update**

I went into Contents and opened the applet in MacOS. It seems to be working now.

**Comment by rayfarer** [comment]
Anot

**Comment by pineapplemachine** [comment]
Good that you got this working. If you have errors again in the future, the most reliable way to run mwde is to open a terminal, `ch` to the root directory, and run `python src/dialog_explorer.py`.
